import { Rating } from "../../interfaces";

export const ratings: Rating[] = [
  {
    anonymous: false,
    author_portrait: "1113cc6f29cbeb293d722a96e76638c3",
    author_username: "michigosang",
    comment:
      "Finally got my order! I ordered nung 10/13/20 and nareceive ko agad ng 10/19/20. Satisfied customer here. Na-install na po nung technician at gumana na po. Thank you!",
    images: [
      "5a82500ab895661b13dc458acac3bbc6",
      "43172fe30815c6cc8c3f19bca14cec00",
    ],
    rating_star: 5,
    product_items: [
      {
        itemid: 6643760845,
        welcome_package_info: null,
        liked: null,
        recommendation_info: null,
        bundle_deal_info: null,
        price_max_before_discount: 969900000,
        image: "751996009153746830caf407458a0390",
        recommendation_algorithm: null,
        is_cc_installment_payment_eligible: false,
        shopid: 73467985,
        can_use_wholesale: false,
        group_buy_info: null,
        reference_item_id: "",
        currency: "PHP",
        raw_discount: 35,
        show_free_shipping: null,
        video_info_list: null,
        images: [
          "751996009153746830caf407458a0390",
          "e9d06abbddcdbbd51a66bd73b7955b77",
          "9aab2ab09067f9e721bccdb4b4d06542",
        ],
        is_preferred_plus_seller: null,
        price_before_discount: 279900000,
        is_category_failed: false,
        show_discount: 35,
        cmt_count: 50,
        view_count: null,
        catid: 18596,
        upcoming_flash_sale: null,
        is_official_shop: false,
        brand: "Western Digital",
        price_min: 129000000,
        liked_count: 227,
        can_use_bundle_deal: false,
        show_official_shop_label: false,
        coin_earn_label: null,
        is_snapshot: 1,
        price_min_before_discount: 199900000,
        cb_option: 0,
        sold: null,
        stock: 6,
        status: 1,
        price_max: 629000000,
        add_on_deal_info: null,
        is_group_buy_item: null,
        flash_sale: null,
        modelid: 21473037632,
        price: 209000000,
        shop_location: null,
        item_rating: null,
        show_official_shop_label_in_title: false,
        tier_variations: [
          {
            images: [
              "9aab2ab09067f9e721bccdb4b4d06542",
              "e9d06abbddcdbbd51a66bd73b7955b77",
            ],
            properties: null,
            type: 0,
            name: "Form Factor",
            options: ['2.5" SATA', "M.2 2280"],
          },
          {
            images: null,
            properties: null,
            type: 0,
            name: "Capacity",
            options: ["120GB", "240GB", "480GB", "1TB"],
          },
        ],
        is_adult: null,
        discount: "35%",
        flag: 0,
        is_non_cc_installment_payment_eligible: false,
        has_lowest_price_guarantee: true,
        snapshotid: 2092171482,
        has_group_buy_stock: null,
        preview_info: null,
        welcome_package_type: 0,
        exclusive_price_info: null,
        name:
          'Western Digital WD Green 1TB 480GB 240GB 120GB 2.5" SATA III or M.2 2280 SSD 6Gb/s Solid State Drive',
        ctime: 1595750992,
        wholesale_tier_list: [],
        show_shopee_verified_label: true,
        show_official_shop_label_in_normal_position: null,
        item_status: "normal",
        shopee_verified: null,
        hidden_price_display: null,
        size_chart: null,
        item_type: 0,
        shipping_icon_type: null,
        label_ids: [13, 1000109],
        service_by_shopee_flag: null,
        model_name: '2.5" SATA,240GB',
        badge_icon_type: null,
        historical_sold: null,
        transparent_background_image: "",
      },
    ],
    tags: null,
  },
  {
    anonymous: false,
    author_portrait: "bd3a40d08c515899c34f21b52fb47e4c",
    author_username: "averyjohnmercado",
    comment:
      "Good packaging and fast delivery. With receipt from the store and warranty from WD. A good buy :) Can't wait to install an OS pag natapos na pc build. :D",
    images: ["c1de8c3d80fa6cfd961096054fbb28a9"],
    rating_star: 5,
    product_items: [
      {
        itemid: 6643760845,
        welcome_package_info: null,
        liked: null,
        recommendation_info: null,
        bundle_deal_info: null,
        price_max_before_discount: 969900000,
        image: "751996009153746830caf407458a0390",
        recommendation_algorithm: null,
        is_cc_installment_payment_eligible: false,
        shopid: 73467985,
        can_use_wholesale: false,
        group_buy_info: null,
        reference_item_id: "",
        currency: "PHP",
        raw_discount: 38,
        show_free_shipping: null,
        video_info_list: null,
        images: [
          "751996009153746830caf407458a0390",
          "e9d06abbddcdbbd51a66bd73b7955b77",
          "9aab2ab09067f9e721bccdb4b4d06542",
        ],
        is_preferred_plus_seller: null,
        price_before_discount: 199900000,
        is_category_failed: false,
        show_discount: 38,
        cmt_count: 40,
        view_count: null,
        catid: 18596,
        upcoming_flash_sale: null,
        is_official_shop: false,
        brand: "Western Digital",
        price_min: 129000000,
        liked_count: 192,
        can_use_bundle_deal: false,
        show_official_shop_label: false,
        coin_earn_label: null,
        is_snapshot: 1,
        price_min_before_discount: 199900000,
        cb_option: 0,
        sold: null,
        stock: 5,
        status: 1,
        price_max: 599000000,
        add_on_deal_info: null,
        is_group_buy_item: null,
        flash_sale: null,
        modelid: 21473037636,
        price: 129000000,
        shop_location: null,
        item_rating: null,
        show_official_shop_label_in_title: false,
        tier_variations: [
          {
            images: [
              "9aab2ab09067f9e721bccdb4b4d06542",
              "e9d06abbddcdbbd51a66bd73b7955b77",
            ],
            properties: null,
            type: 0,
            name: "Form Factor",
            options: ['2.5" SATA', "M.2 2280"],
          },
          {
            images: null,
            properties: null,
            type: 0,
            name: "Capacity",
            options: ["120GB", "240GB", "480GB", "1TB"],
          },
        ],
        is_adult: null,
        discount: "38%",
        flag: 0,
        is_non_cc_installment_payment_eligible: false,
        has_lowest_price_guarantee: false,
        snapshotid: 2076410057,
        has_group_buy_stock: null,
        preview_info: null,
        welcome_package_type: 0,
        exclusive_price_info: null,
        name:
          'Western Digital WD Green 1TB 480GB 240GB 120GB 2.5" SATA III or M.2 2280 SSD 6Gb/s Solid State Drive',
        ctime: 1595750992,
        wholesale_tier_list: [],
        show_shopee_verified_label: true,
        show_official_shop_label_in_normal_position: null,
        item_status: "normal",
        shopee_verified: null,
        hidden_price_display: null,
        size_chart: null,
        item_type: 0,
        shipping_icon_type: null,
        label_ids: [1000109],
        service_by_shopee_flag: null,
        model_name: "M.2 2280,120GB",
        badge_icon_type: null,
        historical_sold: null,
        transparent_background_image: "",
      },
    ],
    tags: null,
  },
  {
    anonymous: false,
    author_portrait: "a99de46195eb090c2729c0b3872caec4",
    author_username: "navinoliverledesma",
    comment:
      "Arrived in Batangas after 2 days. I requested for a mounting screw which they accepted but they did not send any (luckily found a spare in an old laptop). However, the product itself is in excellent condition and I've been using it for 3 days already (after I clean installed Windows 10 on it).",
    images: null,
    rating_star: 5,
    product_items: [
      {
        itemid: 6643760845,
        welcome_package_info: null,
        liked: null,
        recommendation_info: null,
        bundle_deal_info: null,
        price_max_before_discount: 969900000,
        image: "751996009153746830caf407458a0390",
        recommendation_algorithm: null,
        is_cc_installment_payment_eligible: false,
        shopid: 73467985,
        can_use_wholesale: false,
        group_buy_info: null,
        reference_item_id: "",
        currency: "PHP",
        raw_discount: 38,
        show_free_shipping: null,
        video_info_list: null,
        images: [
          "751996009153746830caf407458a0390",
          "e9d06abbddcdbbd51a66bd73b7955b77",
          "9aab2ab09067f9e721bccdb4b4d06542",
        ],
        is_preferred_plus_seller: null,
        price_before_discount: 279900000,
        is_category_failed: false,
        show_discount: 38,
        cmt_count: 63,
        view_count: null,
        catid: 18596,
        upcoming_flash_sale: null,
        is_official_shop: false,
        brand: "Western Digital",
        price_min: 129000000,
        liked_count: 260,
        can_use_bundle_deal: false,
        show_official_shop_label: false,
        coin_earn_label: null,
        is_snapshot: 1,
        price_min_before_discount: 199900000,
        cb_option: 0,
        sold: null,
        stock: 4,
        status: 1,
        price_max: 599000000,
        add_on_deal_info: null,
        is_group_buy_item: null,
        flash_sale: null,
        modelid: 21473037634,
        price: 199000000,
        shop_location: null,
        item_rating: null,
        show_official_shop_label_in_title: false,
        tier_variations: [
          {
            images: [
              "9aab2ab09067f9e721bccdb4b4d06542",
              "e9d06abbddcdbbd51a66bd73b7955b77",
            ],
            properties: null,
            type: 0,
            name: "Form Factor",
            options: ['2.5" SATA', "M.2 2280"],
          },
          {
            images: null,
            properties: null,
            type: 0,
            name: "Capacity",
            options: ["120GB", "240GB", "480GB", "1TB"],
          },
        ],
        is_adult: null,
        discount: "38%",
        flag: 0,
        is_non_cc_installment_payment_eligible: false,
        has_lowest_price_guarantee: true,
        snapshotid: 2110891868,
        has_group_buy_stock: null,
        preview_info: null,
        welcome_package_type: 0,
        exclusive_price_info: null,
        name:
          'Western Digital WD Green 1TB 480GB 240GB 120GB 2.5" SATA III or M.2 2280 SSD 6Gb/s Solid State Drive',
        ctime: 1595750992,
        wholesale_tier_list: [],
        show_shopee_verified_label: true,
        show_official_shop_label_in_normal_position: null,
        item_status: "normal",
        shopee_verified: null,
        hidden_price_display: null,
        size_chart: null,
        item_type: 0,
        shipping_icon_type: null,
        label_ids: [13, 1000109],
        service_by_shopee_flag: null,
        model_name: "M.2 2280,240GB",
        badge_icon_type: null,
        historical_sold: null,
        transparent_background_image: "",
      },
    ],
    tags: [{ tag_description: "Excellent quality " }],
  },
  {
    anonymous: false,
    author_portrait: "cfb08e0e64ee10610e0d6e3f97641bf2",
    author_username: "angelotoribio",
    comment:
      "Very Good quality and authentic no doubt BUT Ninjavan is garbage. Period. Parcel was 4 days late and there were no updates or anything. I wouldve given 5 stars if it wasnt late",
    images: ["70dddf90b8357d6d5e94ebeed815331c"],
    rating_star: 3,
    product_items: [
      {
        itemid: 6643760845,
        welcome_package_info: null,
        liked: null,
        recommendation_info: null,
        bundle_deal_info: null,
        price_max_before_discount: 969900000,
        image: "751996009153746830caf407458a0390",
        recommendation_algorithm: null,
        is_cc_installment_payment_eligible: false,
        shopid: 73467985,
        can_use_wholesale: false,
        group_buy_info: null,
        reference_item_id: "",
        currency: "PHP",
        raw_discount: 35,
        show_free_shipping: null,
        video_info_list: null,
        images: [
          "751996009153746830caf407458a0390",
          "e9d06abbddcdbbd51a66bd73b7955b77",
          "9aab2ab09067f9e721bccdb4b4d06542",
        ],
        is_preferred_plus_seller: null,
        price_before_discount: 199900000,
        is_category_failed: false,
        show_discount: 35,
        cmt_count: 53,
        view_count: null,
        catid: 18596,
        upcoming_flash_sale: null,
        is_official_shop: false,
        brand: "Western Digital",
        price_min: 129000000,
        liked_count: 235,
        can_use_bundle_deal: false,
        show_official_shop_label: false,
        coin_earn_label: null,
        is_snapshot: 1,
        price_min_before_discount: 199900000,
        cb_option: 0,
        sold: null,
        stock: 5,
        status: 1,
        price_max: 629000000,
        add_on_deal_info: null,
        is_group_buy_item: null,
        flash_sale: null,
        modelid: 21473037635,
        price: 129000000,
        shop_location: null,
        item_rating: null,
        show_official_shop_label_in_title: false,
        tier_variations: [
          {
            images: [
              "9aab2ab09067f9e721bccdb4b4d06542",
              "e9d06abbddcdbbd51a66bd73b7955b77",
            ],
            properties: null,
            type: 0,
            name: "Form Factor",
            options: ['2.5" SATA', "M.2 2280"],
          },
          {
            images: null,
            properties: null,
            type: 0,
            name: "Capacity",
            options: ["120GB", "240GB", "480GB", "1TB"],
          },
        ],
        is_adult: null,
        discount: "35%",
        flag: 0,
        is_non_cc_installment_payment_eligible: false,
        has_lowest_price_guarantee: true,
        snapshotid: 2100053942,
        has_group_buy_stock: null,
        preview_info: null,
        welcome_package_type: 0,
        exclusive_price_info: null,
        name:
          'Western Digital WD Green 1TB 480GB 240GB 120GB 2.5" SATA III or M.2 2280 SSD 6Gb/s Solid State Drive',
        ctime: 1595750992,
        wholesale_tier_list: [],
        show_shopee_verified_label: true,
        show_official_shop_label_in_normal_position: null,
        item_status: "normal",
        shopee_verified: null,
        hidden_price_display: null,
        size_chart: null,
        item_type: 0,
        shipping_icon_type: null,
        label_ids: [13, 1000109],
        service_by_shopee_flag: null,
        model_name: '2.5" SATA,120GB',
        badge_icon_type: null,
        historical_sold: null,
        transparent_background_image: "",
      },
    ],
    tags: null,
  },
  {
    anonymous: false,
    author_portrait: "1b0ddf2053743928010541331fe33785",
    author_username: "johnbryce0616",
    comment: "",
    images: ["6a0f1a18ff84912b8310a300ed4ab5c9"],
    rating_star: 5,
    product_items: [
      {
        itemid: 6643760845,
        welcome_package_info: null,
        liked: null,
        recommendation_info: null,
        bundle_deal_info: null,
        price_max_before_discount: 969900000,
        image: "751996009153746830caf407458a0390",
        recommendation_algorithm: null,
        is_cc_installment_payment_eligible: false,
        shopid: 73467985,
        can_use_wholesale: false,
        group_buy_info: null,
        reference_item_id: "",
        currency: "PHP",
        raw_discount: 38,
        show_free_shipping: null,
        video_info_list: null,
        images: [
          "751996009153746830caf407458a0390",
          "e9d06abbddcdbbd51a66bd73b7955b77",
          "9aab2ab09067f9e721bccdb4b4d06542",
        ],
        is_preferred_plus_seller: null,
        price_before_discount: 199900000,
        is_category_failed: false,
        show_discount: 38,
        cmt_count: 63,
        view_count: null,
        catid: 18596,
        upcoming_flash_sale: null,
        is_official_shop: false,
        brand: "Western Digital",
        price_min: 129000000,
        liked_count: 260,
        can_use_bundle_deal: false,
        show_official_shop_label: false,
        coin_earn_label: null,
        is_snapshot: 1,
        price_min_before_discount: 199900000,
        cb_option: 0,
        sold: null,
        stock: 7,
        status: 1,
        price_max: 599000000,
        add_on_deal_info: null,
        is_group_buy_item: null,
        flash_sale: null,
        modelid: 21473037635,
        price: 129000000,
        shop_location: null,
        item_rating: null,
        show_official_shop_label_in_title: false,
        tier_variations: [
          {
            images: [
              "9aab2ab09067f9e721bccdb4b4d06542",
              "e9d06abbddcdbbd51a66bd73b7955b77",
            ],
            properties: null,
            type: 0,
            name: "Form Factor",
            options: ['2.5" SATA', "M.2 2280"],
          },
          {
            images: null,
            properties: null,
            type: 0,
            name: "Capacity",
            options: ["120GB", "240GB", "480GB", "1TB"],
          },
        ],
        is_adult: null,
        discount: "38%",
        flag: 0,
        is_non_cc_installment_payment_eligible: false,
        has_lowest_price_guarantee: true,
        snapshotid: 2110891868,
        has_group_buy_stock: null,
        preview_info: null,
        welcome_package_type: 0,
        exclusive_price_info: null,
        name:
          'Western Digital WD Green 1TB 480GB 240GB 120GB 2.5" SATA III or M.2 2280 SSD 6Gb/s Solid State Drive',
        ctime: 1595750992,
        wholesale_tier_list: [],
        show_shopee_verified_label: true,
        show_official_shop_label_in_normal_position: null,
        item_status: "normal",
        shopee_verified: null,
        hidden_price_display: null,
        size_chart: null,
        item_type: 0,
        shipping_icon_type: null,
        label_ids: [13, 1000109],
        service_by_shopee_flag: null,
        model_name: '2.5" SATA,120GB',
        badge_icon_type: null,
        historical_sold: null,
        transparent_background_image: "",
      },
    ],
    tags: null,
  },
  {
    anonymous: false,
    author_portrait: "4518d0dd7e7e33fed948923082044837",
    author_username: "gosachisophia",
    comment:
      "Fast shipping and well-packaged. Ssd itself is great, 100% healthy in hdsentinel and works effectively as a fast boot drive. Just take note that it doesn't come with screws or a sata cable. Really good deal pa rin, esp with the warranty.",
    images: null,
    rating_star: 5,
    product_items: [
      {
        itemid: 6643760845,
        welcome_package_info: null,
        liked: null,
        recommendation_info: null,
        bundle_deal_info: null,
        price_max_before_discount: 969900000,
        image: "751996009153746830caf407458a0390",
        recommendation_algorithm: null,
        is_cc_installment_payment_eligible: false,
        shopid: 73467985,
        can_use_wholesale: false,
        group_buy_info: null,
        reference_item_id: "",
        currency: "PHP",
        raw_discount: 35,
        show_free_shipping: null,
        video_info_list: null,
        images: [
          "751996009153746830caf407458a0390",
          "e9d06abbddcdbbd51a66bd73b7955b77",
          "9aab2ab09067f9e721bccdb4b4d06542",
        ],
        is_preferred_plus_seller: null,
        price_before_discount: 199900000,
        is_category_failed: false,
        show_discount: 35,
        cmt_count: 53,
        view_count: null,
        catid: 18596,
        upcoming_flash_sale: null,
        is_official_shop: false,
        brand: "Western Digital",
        price_min: 129000000,
        liked_count: 235,
        can_use_bundle_deal: false,
        show_official_shop_label: false,
        coin_earn_label: null,
        is_snapshot: 1,
        price_min_before_discount: 199900000,
        cb_option: 0,
        sold: null,
        stock: 5,
        status: 1,
        price_max: 629000000,
        add_on_deal_info: null,
        is_group_buy_item: null,
        flash_sale: null,
        modelid: 21473037635,
        price: 129000000,
        shop_location: null,
        item_rating: null,
        show_official_shop_label_in_title: false,
        tier_variations: [
          {
            images: [
              "9aab2ab09067f9e721bccdb4b4d06542",
              "e9d06abbddcdbbd51a66bd73b7955b77",
            ],
            properties: null,
            type: 0,
            name: "Form Factor",
            options: ['2.5" SATA', "M.2 2280"],
          },
          {
            images: null,
            properties: null,
            type: 0,
            name: "Capacity",
            options: ["120GB", "240GB", "480GB", "1TB"],
          },
        ],
        is_adult: null,
        discount: "35%",
        flag: 0,
        is_non_cc_installment_payment_eligible: false,
        has_lowest_price_guarantee: true,
        snapshotid: 2100053942,
        has_group_buy_stock: null,
        preview_info: null,
        welcome_package_type: 0,
        exclusive_price_info: null,
        name:
          'Western Digital WD Green 1TB 480GB 240GB 120GB 2.5" SATA III or M.2 2280 SSD 6Gb/s Solid State Drive',
        ctime: 1595750992,
        wholesale_tier_list: [],
        show_shopee_verified_label: true,
        show_official_shop_label_in_normal_position: null,
        item_status: "normal",
        shopee_verified: null,
        hidden_price_display: null,
        size_chart: null,
        item_type: 0,
        shipping_icon_type: null,
        label_ids: [13, 1000109],
        service_by_shopee_flag: null,
        model_name: '2.5" SATA,120GB',
        badge_icon_type: null,
        historical_sold: null,
        transparent_background_image: "",
      },
    ],
    tags: null,
  },
];
